# Generated by Django 3.0.2 on 2020-02-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleMusic', '0004_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
