# Generated by Django 3.0.2 on 2020-02-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleMusic', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
