# Generated by Django 3.0.2 on 2020-02-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleMusic', '0011_remove_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
