# Generated by Django 3.0.2 on 2020-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleMusic', '0014_auto_20200213_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsImage', models.FileField(upload_to='')),
                ('postDate', models.DateField()),
                ('newsTitle', models.CharField(max_length=255)),
                ('news', models.TextField()),
            ],
        ),
    ]
